### ISSUE TITLE
503 Service Unavailable message upon testing

### ISSUE THREAD

**Issue by bkaminski** [FotieMConstant/geek-quote-api#19]
**Describe the bug**
PHP error 503 Service Unavailable

Is this a known issue?

**Comment by FotieMConstant** [comment]
Hi there @bkaminski, apologies for the late reply, due to the taking down of the free tier by heroku, which is where the app was initially hosted. the api was temporary down for some time.

However, this issue has just been resolved and you can now call the api from the new domain which was moved to vercel earlier today.

New domain: https://geek-quote-api.vercel.app/

**Comment by bkaminski** [comment]
Thanks a lot! I :heart: nerdy quotes!!!

**Comment by FotieMConstant** [comment]
My pleasure @bkaminski. Remember you can always get your app listed in this repo as “apps using our api” after integrating our api.

Have a nice one

**Comment by bkaminski** [comment]
@FotieMConstant thanks! Sorry for the late response. I appreciate your work.
